#! /bin/bash

if [[ -n "$1" ]]
then
  branch="$1"
else
  branch="freerange-updates"
fi

timestamp=$(date +%s)
schema=(event study)
for i in ${schema[@]} ; do
  echo "Updating $i.json"
  curl --silent -H"If-None-Match: $timestamp" "https://raw.githubusercontent.com/cdsig/CDSIG-Schema/$branch/$i.json" > src/schema/original/$i.json
  cat src/schema/original/$i.json | ./scripts/dereference-schema > src/schema/$i.json
done

npx prettier -w src/schema/*.json
